name=RCLink
version=0.1.0
author=Nathan Rab
maintainer=Nathan Rab
sentence=Radiocontrole simples entre ESP32-S3 usando ESP-NOW Long Range.
paragraph=Canais RC, mensagens, failsafe automatico, servos, ESC, joystick e LEDs. Feita para ser usada pelo ambiente RC32S3.
category=Communication
url=https://github.com/
architectures=esp32
